// src/components/ui/progress.tsx
import React from 'react';

interface ProgressProps {
  value: number;
  max?: number;
  className?: string;
}

export function Progress({ value, max = 100, className = '' }: ProgressProps) {
  const percentage = Math.min(Math.max((value / max) * 100, 0), 100);
  
  return (
    <div className={`relative h-4 w-full overflow-hidden rounded-full bg-gray-200 dark:bg-gray-800 ${className}`}>
      <div
        className="h-full bg-blue-600 transition-all duration-300 ease-in-out"
        style={{ width: `${percentage}%` }}
      />
    </div>
  );
}

// vue-frontend/src/components/ui/Progress.vue
<template>
  <div :class="progressClasses">
    <div
      :class="fillClasses"
      :style="{ width: `${percentage}%` }"
    />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { cn } from '@/lib/utils'

interface Props {
  value: number
  max?: number
  class?: string
}

const props = withDefaults(defineProps<Props>(), {
  max: 100
})

const percentage = computed(() => Math.min(Math.max((props.value / props.max) * 100, 0), 100))

const progressClasses = computed(() => 
  cn('relative h-4 w-full overflow-hidden rounded-full bg-gray-200 dark:bg-gray-800', props.class)
)

const fillClasses = 'h-full bg-blue-600 transition-all duration-300 ease-in-out'
</script>
